spring.application.name=api_blog

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/api_blog
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true

# JWT Secret (move out of source code)
jwt.secret=${JWT_SECRET}

# Pinata (use environment variables)
pinata.jwt=${PINATA_JWT}
pinata.api-key=${PINATA_API_KEY}
pinata.secret-api-key=${PINATA_SECRET_KEY}

# Logging
logging.level.com.example.api_blog=DEBUG